<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 22" tests="1" total_time="Finished in: 3.03 secs."/>
<test location="/Users/apple/Documents/workspace/django_program/superlists/functional_tests.py" status="error" test="NewVisitorTest.test_can_start_a_list_and_retrieve_it_later" time="">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "/Users/apple/Documents/workspace/django_program/superlists/functional_tests.py", line 35, in test_can_start_a_list_and_retrieve_it_later
    inputbox.send_keys(Keys.ENTER)
NameError: name 'Keys' is not defined
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="django_program functional_tests.py (1)"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
